### PR TITLE
rename function to enable / disable nagle algorithm

### PR DESCRIPTION
**Pull request by stlankes**

### CODE REVIEW

**Review by mkroening — APPROVED** [review]
Looks good to me. This function is not used anywhere yet though, right?

We might want to name it `sys_tcp_set_nodelay` as done in `std` though. And a corresponding `sys_tcp_nodelay` as getter might be useful.

You can go ahead an merge this though, I have no strong opinion on this. :)

**Comment by stlankes** [comment]
Yes, but a getter function requires a new version of smoltcp (see smoltcp-rs/smoltcp/pull/642).

**Comment by stlankes** [comment]
@mkroening Why does CI fail? Any idea?

**Comment by mkroening** [comment]
> @mkroening Why does CI fail? Any idea?

Seems to be quite strange indeed. I think we could disable the windows CI for now.

**Comment by mkroening** [comment]
> bors r+

You also need to remove the job from `bors.toml`.

**Pull request merged**
