### PR TITLE
Rework CI

### PR DESCRIPTION
**Pull request by mkroening**
I reworked this CI in similar to https://github.com/hermitcore/libhermit-rs/pull/230.

### CODE REVIEW

**Comment by mkroening** [comment]
This is WIP for now.

**Comment by mkroening** [comment]
This is ready for review now.

**Review by stlankes — APPROVED** [review]
bors r+

**Comment by mkroening** [comment]
Oh no, I had another typo in the bors file (`macOS` instead of `macos`).

**Comment by stlankes** [comment]
bors try

**Pull request merged**
