### PR TITLE
removing kernel targets

### PR DESCRIPTION
**Pull request by stlankes**
In #197 we discuss to use x86_64-unknown-none target instead of the special `kernel` target. Also the aarch64 port has to useaarch64-unknown-none-softfloat. The floating point unit should not use in the kernel space.

### CODE REVIEW

**Comment by stlankes** [comment]
bors try

**Comment by mkroening** [comment]
Does that mean, we'll produce ELF files without our magic number for now, @stlankes?

**Comment by stlankes** [comment]
No, I still want to produce ELF files with the magic number for a standalone application. We are able to modify the number after building the library or before linking the application.

However, the target `aarch64-unknown-none-softfloat` doesn't build a dynamic relocatable library. If this will not changed, we need our own `aarch64-unknown-hermitkernel` target (see rust-lang/rust#92670). We need a kernel target to disable within the kernel the SIMD instruction and the red-zone.

**Comment by stlankes** [comment]
At this stage, I don't think that we are able to switch `aarch64-unknown-none-softfloat`? @mkroening Do you think that we should use `x86_64-unknown-none`?

**Comment by mkroening** [comment]
Should this be closed then, @stlankes? I'll have a look at aligning our x86 target with `x86_64-unknown-none`.

**Comment by mkroening** [comment]
Resolved by https://github.com/hermitcore/libhermit-rs/pull/395.

**Pull request closed without merging**
