### PR TITLE
creating of a classical cargo package layout 

### PR DESCRIPTION
**Pull request by stlankes**
- solve issue #51

### CODE REVIEW

**Comment by jounathaen** [comment]
I like it!
However, it only solves #51 only partially, because the hello-world example from rusty-demo is still missing.

**Comment by stlankes** [comment]
Hm, it is part of `rusty_demo`. Take a look at [https://github.com/stlankes/rusty-hermit/blob/layout/examples/demo/src/main.rs#L30](https://github.com/stlankes/rusty-hermit/blob/layout/examples/demo/src/main.rs#L30)

**Comment by jounathaen** [comment]
Yes, that is what #51  is about

**Comment by stlankes** [comment]
The `hello_world` example shows how it works with hermit-sys from cates.io (see [https://github.com/hermitcore/rusty-demo/blob/master/Cargo.toml#L8-L9](https://github.com/hermitcore/rusty-demo/blob/master/Cargo.toml#L8-L9). The examples in this repository use a relative path to `hermit-sys` (see [https://github.com/stlankes/rusty-hermit/blob/layout/examples/demo/Cargo.toml#L12](https://github.com/stlankes/rusty-hermit/blob/layout/examples/demo/Cargo.toml#L12). But your are right, a hello world example would be als great for this repository.

**Comment by stlankes** [comment]
Not all examples are running in the CI. But only the network benchmark is missing.

**Pull request merged**
