### PR TITLE
PR #112 requires a socket handle to consume the buffer

### PR DESCRIPTION
**Pull request by stlankes**
in addition, we revised the benchmark to measure the stream bandwidth and supports now also non-blocking streams.

### CODE REVIEW

**Comment by stlankes** [comment]
@mustermeiszer Or do I forget something?

**Comment by mustermeiszer** [comment]
@stlankes  device.rs looks good to me. 

What are the changes in the bw-benchmark-client good for?

**Comment by stlankes** [comment]
If the client use a non-blocking stream, the write operation is able to fail because the resources are temporarily not available. In this case, we have to reinitiate the last write operation.

**Pull request merged**
