### PR TITLE
Add netbench runner

### PR DESCRIPTION
**Pull request by mkroening**
This little script helps running `netbench`.

I am not sure if we would even want such a thing upstream. The amount of RAM and the arguments for `netbench` has still to be debated about.

What do you think?

### CODE REVIEW

**Comment by stlankes** [comment]
Cool, can you remove `RUSTFLAGS="-Clinker-plugin-lto" in your script. It isn't longer supported (see #125). If you use KVM, you can use the flag `-cpu host`. It should work.

**Comment by mkroening** [comment]
I updated the PR but faced #128.

**Comment by mkroening** [comment]
I just rebased on latest master and added a short usage comment on top of the script.

**Comment by stlankes** [comment]
bors retry

**Pull request merged**
