### PR TITLE
build.rs: Simplify rerun-if-changed

### PR DESCRIPTION
**Pull request by mkroening**

### CODE REVIEW

**Comment by stlankes** [comment]
Does it work? If I remember correctly, in the past it doesn't work correctly.

**Comment by mkroening** [comment]
So there are two semantic differences to the current state:

1. We now emit rerun-if-changed when downloading the kernel. This should not be a problem, I think.
2. We now emit one rerun-if-changed for the whole libhermit-rs project folder instead of one rerun-if-changed for every single libhermi-rs source file. This works correctly. Before, we filtered libhermit-rs' target directory though, which is not the case now. This means that if we build libhermit-rs' kernel manually and then hermit-sys, the kernel compilation is being startet, although it is unnecessary. This job will finish very quickly though, as no kernel source file has changed. Also this case should happen very rarely, if at all. In this case, compilation takes 1 second instead of 0.10 seconds on my machine.

We could explicitly list all of libhermit-rs' subdirectories and filter the target directory, but I think this would not be worth the extra code and cargo instructions. What do you think?

**Comment by mkroening** [comment]
Ah, actually when downloading the kernel and building it in tree, this rerun-if-changed configuration is too sensitive and annoying. I'll change this to not include the kernel's target directory.

**Comment by mkroening** [comment]
Okay, instead of filtering target inside the downloaded kernel source, I configured the target directory to always be outside the kernel source. It should be cleaner that way anyways, as we don't touch the kernel source for building at all now.

What do you think? :)

**Pull request merged**
