### PR TITLE
Replace loader submodule with release

### PR DESCRIPTION
**Pull request by mkroening**

### CODE REVIEW

**Comment by mkroening** [comment]
bors try

**Comment by mkroening** [comment]
bors cancel

**Comment by mkroening** [comment]
bors try

**Comment by mkroening** [comment]
bors try-

**Comment by mkroening** [comment]
bors try

**Comment by mkroening** [comment]
bors try

**Comment by stlankes** [comment]
Do we need to change the README?

**Comment by mkroening** [comment]
> Do we need to change the README?

Ah, yes. I referred to the released loader binary instead of explaining how to build the loader, if that's okay.

**Comment by mkroening** [comment]
bors r=stlankes

**Pull request merged**
