### PR TITLE
using of the asm feature to improve the performance of basic functions

### PR DESCRIPTION
**Pull request by stlankes**
-  PR uses rust-lang/compiler-builtins#365 to improve the performance
- fix broken CI and build the bootloader on windows correctly

### CODE REVIEW

**Review by jschwe — COMMENTED** [review]
Regarding windows CI, also have a look at https://github.com/hermitcore/rusty-hermit/pull/79.
You could add the line to this PR.

**Review by jschwe — CHANGES_REQUESTED** [review]
According to the [documentation]( https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files) you should use the following command with powershell:
`echo "mypath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append`

**Review by jbreitbart — APPROVED** [review]

**Comment by stlankes** [comment]
bors retry

**Comment by stlankes** [comment]
bors retry

**Comment by stlankes** [comment]
bors retry

**Pull request merged**
