### PR TITLE
Include `tcp` in the default features of `hermit-sys`

### LINKED ISSUE #435: Include `tcp` in the default features of `hermit-sys`
This is a pitfall. With an unikernel targeting cloud and HPC environments, having network support enabled is the better default. It can be switched off if needed.

### PR DESCRIPTION
**Pull request by stlankes**
TCP is an important feature and should be part of the default features

Closes #435.

### CODE REVIEW

**Comment by jounathaen** [comment]
I'm not sure if we should add `dhcpv4` then as well :thinking:

**Comment by stlankes** [comment]
At least for our CI tests is `dhcpv4` not required.

**Comment by jounathaen** [comment]
I'm not talking about the CI but about the user experience. Then a "microservice" would work out of the box.

**Comment by stlankes** [comment]
Ok, I will change it.

**Review by mkroening — APPROVED** [review]

**Pull request merged**
